// SPDX-License-Identifier: Apache-2.0
:doctype: article

= The Death of Free Speech

In the last century, veterans have fought and died in two major world wars. Some of these men fought in conditions we
can't even imagine, soiling themselves in their foxholes, with their feet rotting in their boots. It seems over last 10
to 15 years, we have entirely lost sight of what they fought for, as we have discarded free speech in favour of granting
everyone the right not to have to listen to anything they don't like.

The latest debacle of 13 Dalhousie students who said stupid things on Facebook is a prime example. The only real reason
the university administrators punished them by suspending them from clinical duties is that their remarks targeted women,
which is a hot button issue, particularly at universities where women have been attacked. If their remarks had targeted
communists, old people, North Koreans, terrorists, or any other group that is not a hot button issue, would the university
have done anything? Would it be a national news item? Would anyone be asking "is it enough?" Would anyone even notice?

Once one freedom is lost, others simply follow. In this case, the Royal College of Dental Surgeons has indicated that if
they can't get the names of the 13 students, they will basically make the all the graduates of that class prove they were
not the 13. How exactly can you prove you were not part of a Facebook group that no longer exists? This is guilty until
proven innocent, a simple reversal of our most fundamental law. Seems the Alberta College is following the lead of the
Royal College, and will want proof of character. More will surely follow the bandwagon in true "me too" fashion.

If the past record of overreaction to minor bad deeds is any indication, once political pressures change to something else,
the punishers will simply follow the new pressure and punish people for something else. Perhaps 10 or 20 years from now,
male students making similar comments on Facebook will be ignored. Is that fair to these 13? Is it fair for anyone to be
punished just for a political climate they didn't create? Is it fair that all male students of that class will now have
to prove their character to some entirely subjective process in order to practice what they paid and studied for over
the years? It is fair that students can never really know what they can and cannot say in their personal time without be
punished at school?

Our free speech laws are not absolute, if these students said anything that is libelous or slanderous, they can be charged
accordingly. The male students of that class should take the university to task for overreacting rather than using their
heads - what people say on their Facebook page is their own damn business, and if they did anything illegal, that is a
matter for the police and the courts. It is not up to universities to act as some kind of half-assed god-only-knows-what-they-react-to-next police force.
The same goes for the various dentist colleges, the male students should take them to task for the same reasons. One has
to ask if some of these administrators are simply over-stepping their bounds in their zeal, according to the regulations
and policies of their respective university or college.

This kind of nonsense has to stop. While there are still sensible people out there, there clearly are nowhere near enough
of them. We are already past the tipping point, where the only way forward is for people who wind up on the business end
of the political correctness stick to fight for their rights. If enough people stand and say enough of this nanny state
rubbish, perhaps we can return to a more sensible climate, like we had when I was growing up. People entering their teen
years today won't even know the difference, they have been raised in this climate of silliness. And that is what concerns
me the most.
