// SPDX-License-Identifier: Apache-2.0
:doctype: article

= The importance of privacy settings in social media

I was thinking about this whole scandal with the 13 students at Dalhousie, and realized a couple of things.

The first is that these guys were just your average, garden variety, plain Jane, unremarkable assholes. They were no more
or less of an asshole than:

* those who bemoan the existence of homosexuals
* someone I once saw on TV claiming the superiority of white people over others, that this is somehow related to their blood
* some guy who screamed at me out of his car window for riding my bike on a road that has a bicycle route sign on it
* guys I used to work with at a construction job who said all kinds of crude things about women

I've heard many guys in my time trash talking about women, and I seriously doubt the actual content of what these 13
students said on their facebook group was any worse than the crap I've heard before. I'm sure, like all the others, they
knew they were trash talking, and did not mean it seriously. To some extent, it is normal for guys who hang around each
other a lot to say stupid crude things about women as a private joke. As a rule, when guys do this, they know they're
being assholes, and certainly wouldn't say things like that in front of any women, since they obviously wouldn't want to
hear it.

That's where the second realization came in: the only thing these guys really did wrong was they treated their facebook
group like a private hangout that nobody else would read.

If these guys had used the facebook privacy settings to automatically make new posts private, and tested those settings
with the tool that lets you see how your facebook page looks to John Q Public, then nobody would ever have heard about it.
These women wouldn't have known, these guys would have eventually tired of their group and deleted it, and moved on with
their lives along some reasonably mundane path like everyone else they graduated with.

Unfortunately, political correctness has long been teaching us that we all have the right to never be offended. Today's
university students are simply not old enough to have been blessed with existence before political correctness arrived on
the scene to brainwash the masses with their bullshit.

I could probably find 1,000 examples of people being assholes on YouTube, some of whom undoubtedly are trash talking women
just as bad or worse than these guys were. But since nobody complained about how they were personally offended by it, no
one gives a damn.

Before the PC "movement", you knew what the rules were, what to say, what not say, and what would happen if you broke them.
But now, you just don't know what people will call offensive, how big of a response you'll get, what might go viral on
social media, what could become a scandal, or how this can affect your life - such as your job prospects.

Pretty much anything offensive you say could spin out of control if the wrong audience gets a hold of it. It's safe to say
these 13 students have provided us all a valuable lesson about privacy and speech.

Some good rules of thumb would be:

* If you really want to talk about topics that are obviously offensive to some people, then assert control over your usage
of social media.
* The degree to which you can assert control over social media varies widely - make sure you know the implications *before*
you make that offensive posting, afterwards might be too late.
* Do you really need to put absolutely everything you have to say online? In some cases you're better off to keep your
conversation offline over a few beers at a house party.

I don't know what, if any, discussion youngsters get in in grade school about this topic, but it should be discussed to
help prevent further incidents like this.
