// SPDX-License-Identifier: Apache-2.0
:doctype: article

= L'nui - We all need to learn about our Natives

I grew up in a small town where we had "the" Indian kid and "the" black kid. In those days, an Indian was necessarily a
Canadian native, not someone from India. His family seemed like the others on our street, they were nice people. They had
a family tragedy that had occurred before I was born, the sort of thing that could happen to any family, that you
occasionally read about in the paper.

I spent the bulk of my life as a kid in Vancouver Island, BC. I don't know about the rest of BC, but on the island you
cannot possibly live there for any length of time and not get to know natives. At some point, you meet natives at school,
at work, a friend of a friend, or in your neighbourhood. You probably don't know natives by all of those means at the
same time, but you always know some.

In BC, you see totem poles in various places, and native articles for sale like smoked salmon. The town of Duncan has
some large murals on the buildings that you just can't miss if you drive through the main drag.

Yet the average non-native person graduating from high school in this country probably knows approximately nothing about
our natives, except for whatever mixture of fact and fiction they may have learned outside of school along the way. My
only education of natives was limited to one elementary school talk in the auditorium by some natives, and all I remember
of what they said is that natives don't cover flap their hands over their mouths and say "wa-wa-wa-wa".

I recently read an article in a local small newspaper about a Mi'kmaw woman who has travelled around the world with
messages of peace and love, and wears a t-shirt that says "L'nui" on the front (I don't remember her name, and can't
seem to find any reference to her online). She believes her people need to reclaim their language, that too many
Mi'kmaw can't speak it.

As I have recently decided to read about the Mi'kmaw, I knew right right away that L'nu is an old Mi'kmaw word that
means "the people", which I take to mean all Mi'kmaw people everywhere, not just your local village. I've learned a few
of their words, and it seems adding an "i" on the end of a word adds an "of" meaning. So I would interpret the t-shirt
that says "L'nui" to mean "one of the people".

The Mi'kmaw publish a number of books about their legends and experiences that can be found at any local library. I read
one recently that explained some of the details of what went on in the residential schools, and some facts about the
history in this province I would never had known if I had not read it.

As I heard a news story a night or two ago about how some native parents weren't even informed when their children died
in residential schools, it became clear to me that learning about natives should be a basic part of the school curriculum
in this country.

I agree that all Mi'kmaw should learn their language, just as every Quebecer learns Quebecois. But that's merely a good
start - I'm sure all of our native tribes have suffered some degree of language and cultural loss. Every native here
should learn their own language, just as the Chinese learn their own language as well as English.

But if the rest of us continue in ignorance of our natives, how can we ever expect to mend the rift that has existed
between us for so long? We not only don't know much about them, we don't even know what those before us did to them - a
perfect example of historical revisionism if I ever saw one.
