:doctype: article

= The shortcomings of the western message to China about Uighurs

For a little over a century (1880 - 1996), Canada had a residential school system that suppressed the native way of life.
It was an ill-fated attempt to turn natives into Canadians. For some reason you and I can't understand since we weren't
there at the time, the political climate of the day seemed to think being Canadian and being native was some kind of
contradiction, that somehow one precluded the other.

All that Canada had to do to make the biggest difference in our history was to recognize there is no such contradiction.
To ensure that natives learn the English language and history, but to allow them to continue with their dances, songs,
long houses, stories, elborate forms of dress, and all the other things that they had beeen doing before we arrived.
That way, if some natives wanted to go to a city, they could work alongside others and speak the language, and know historical
figures and other details that tend to come up in conversation.

We didn't do that because we were just too racist at the time to take the native way of life seriously. We saw savages,
and acted savagely towards them. What the Chinese are doing to the Uighurs is really no different, they are simply trying to
assimilate Uighurs into China. We raped kids, beat them, called them names. To put things into perspective, a 16 year old
girl was beaten to death in front of all the other kids in the lunch room just for saying she was looking forward to
being home in a few weeks, when she would have been released for completing the program.

We're not in any position to just sit back and declare a genocide in China just because we added that word to our political
vocabulary in the last few years as we finally admit what we did. That's just being a self-righteous ass. The message we
should be providing to China is to learn from our mistake - if they persist in their course with the Uighurs, they may
one day have the the same shame we do around what they did. All that China has to do to avoid this fate is to embrace
the Confucian proverb "study the past if you would define the future" - a strikingly similar statement to one popularized
by Winston Churchill: "those who fail to study history are doomed to repeat it".

This is a universal truth that people the world over can relate to in some way. The western message to China should be
to learn from our conquerors past, our arrogant belligerent indifference to anything other, to find a way to teach the
Uighers how to be Chinese citizens without stripping away what makes them Uighur. That there is no contradiction, so don't
artifically create one purely due to current myopic political intolerance that will likely change in the next few decades,
just as it has here and elsewhere. We should be asking China to be a leader and succeed where we have failed, by
integrating the Uighurs in a way that is not represssive.

That way, instead of coming across as holier than thou, we can come across as genuinely recognizing we are no better,
that this kind of thing has happened before and will happen again, but that doesn't mean we have to just stand by and
let it happen. There's no more need to create a further divide between China and the west than there is to create one
between the Uighurs and the rest of China.

At the same time, the Olympics is supposed to be the one bright shiny spot in the universe where all countries can agree
on something unambiguously - who is the best athlete. Half the sports are objective, there is no debate who ran the fastest
or threw the farthest. The other half are more debatable and subjective, like gymnastics and figure skating. Either way,
there is a process, and there are a number of judges who do a reasonable job of being fair more often than not.

The Olympics are supposed to bring disparate, very different ways of life together. Athletes are able to have relationships
that would otherwise be impossible. A great example is the story of an American athlete (I can't recall who and can't find
the reference) whose wife supported him while he trained relentlessly for hours every day. He started to win at events,
and became an olympian. Along the way, he met a Russian athlete who was the champion to beat. He stated on TV at the time
that he respected the Russian, and had rapport with him. He did eventually beat the Russian (not by much) at one of the games.

The Olympics should not be about protests against a country unless it is directly related to the handling of the Olympics
itself. The games should be free of politics and grandstanding, otherwise they just become another platform for further
division. We need world leaders who can bridge gaps, and that doesn't seem to be happening of late.
