// SPDX-License-Identifier: Apache-2.0
:doctype: article

= What girls get wrong about guys

There is a trope out there that Barbara Streisand is ugly, not as pretty as others, etc. I recall a moment when I had a
roommate, and we were watching some show where this topic came up. We looked at each other in bewilderment, and he said
exactly what I was thinking - that she's gorgeous - with a "what the actual f" look on his face.

I've come to see that women inherently misunderstand how men see women, because they never ask! At the end of the day, a
lot of the significant difference between how women see themselves versus how men see them boils down to girl toys
versus boy toys as children.

Boys play with He-Man, GI Joe, and other hero characters. The boy knows this is entirely un-freakin-real. He is never
going to open his door one day and see a large man in rippling muscles and a skimpy homoerotic blue and red outfit
brandishing a sword and loudly crying "By the power of GreySkull". Unless it's Hallloween, and then it's just some older
kid down the street.

Girls play with Barbies. Initially, in the 60s girls would get a dollhouse, replete with items like an oven and a vacuum
cleaner. Basically, a house girl, which is what most 60s women did. Barbie reflected a degree of reality. When boys see
Barbies, they see the a girl version of unreality - they do not grow up expecting to see women with perfect conical tits,
rounded asses, slim physiques, one skin tone, no distinguishing marks, ready to vacuum and cook. Only girls suffer from
Barbie brain damage.

Boys generally don't bother to explain to girls as they grow up that they value a fun person more than physical traits.
Good looks don't hurt, sure a guy wants to hang with a gorgeous girl. But guys also generally want to bone some of their
friends moms, who do not look like a magazine cover. Any mature male at some point in his life meets a girl who he
doesn't think much of at first, but changes his mind as he spends time with her - but he won't tell her that, because it
is kind of assholish to say "you used to be kind of ugly, but now I wanna tap that ass cause I've gotten to like you".
After all, as a girl, when's the last time you told a guy that?

The point being, girls and boys grow up in separate bubbles, where they have different views of female beauty, and
neither ever asks the other what they honestly think about the importance of looks versus substance. Really, they both
want substance, but the magazines and movies make it seem uncool to say so, with all their airbrushed makeup bullshit.

If you feel some inadequacy as a female, there's a fairly good chance that guys who know you don't share it. Sure, guys
think trashy thoughts when you walk down the street, and some might jokingly talk trash without you hearing it, some
crack about your tits or shirt or mole or whatever - just like you do with your girlyfriends at some guys who walk
by. But guys you know mostly don't see you half as harshly as you see yourself.

I wish parents were better at teaching their girls that guys in real life are not the simple tropes you see on TV, any
more than giels are, and are not nearly as obsessed with female body image as girls are. It's something every dad should
mention at some point, and not just to his own daughter.
